name:                hack
version:             0.1.0.0
github:              d3zd3z/hack
license:             BSD3
author:              David Brown
maintainer:          davidb@davidb.org
copyright:           2017 David Brown

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            ZFS-based snapshotting backup utilities
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/d3zd3z/hack#readme>

dependencies:
- aeson >= 1.1 && < 1.3
- attoparsec >= 0.13 && < 0.14
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 0.11
- containers >= 0.5 && < 0.6
- hslogger >= 1.2 && < 1.3
- monad-loops >= 0.4 && < 0.5
- mtl >= 2.2 && < 2.3
- optparse-applicative
- parsec >= 3.1 && < 3.2
- path >= 0.5 && < 0.7
- path-io >= 1.2 && < 1.4
- time >= 1.8 && < 2.0
- typed-process >= 0.1 && < 2
- text
- unix >= 2.7 && < 2.8
- vector >= 0.12 && < 0.13
- yaml >= 0.8 && < 0.9
- weave

library:
  source-dirs: src

executables:
  hack:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hack

tests:
  hack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hack
