name:                hack
version:             0.1.0.0
github:              d3zd3z/hack
license:             BSD3
author:              David Brown
maintainer:          davidb@davidb.org
copyright:           2017 David Brown

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            ZFS-based snapshotting backup utilities
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/d3zd3z/hack#readme>

dependencies:
- aeson >= 1.1 && < 1.2
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 0.11
- containers >= 0.5 && < 0.6
- optparse-applicative
- path >= 0.5 && < 0.6
- path-io >= 1.2 && < 1.3
- time >= 1.6 && < 2.0
- typed-process >= 0.1 && < 2
- text
- yaml >= 0.8 && < 0.9

library:
  source-dirs: src

executables:
  hack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hack

tests:
  hack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hack
