name:                hack
version:             0.1.0.0
github:              d3zd3z/hack
license:             BSD3
author:              David Brown
maintainer:          davidb@davidb.org
copyright:           2017 David Brown

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            ZFS-based snapshotting backup utilities
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/d3zd3z/hack#readme>

dependencies:
- aeson >= 1.1 && < 1.3
- attoparsec >= 0.13 && < 0.14
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 0.11
- conduit >= 1.3 && < 1.4
- containers >= 0.5 && < 0.6
- cryptonite >= 0.25 && < 0.26
- exceptions >= 0.8 && < 0.9
- free >= 5.0 && < 5.1
- hslogger >= 1.2 && < 1.3
- lens >= 4.16 && < 4.17
- memory >= 0.14 && < 0.15
- optparse-applicative
- parsec >= 3.1 && < 3.2
- path >= 0.5 && < 0.7
- path-io >= 1.2 && < 1.4
- pipes >= 4.3 && < 4.4
- pipes-bytestring >= 2.1 && < 2.2
- pipes-group >= 1.0 && < 1.1
- pipes-zlib >= 0.4 && < 0.5
- time >= 1.8 && < 2.0
- transformers >= 0.5 && < 0.6
- typed-process >= 0.1 && < 2
- text
- unix >= 2.7 && < 2.8
- yaml >= 0.8 && < 0.9

library:
  source-dirs: src

executables:
  hacke:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hack

tests:
  hack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hack
    - weave
    - directory >= 1.3 && < 1.4
    - random >= 1.1 && < 1.2
    - random-fu >= 0.2 && < 0.3
    - regex-tdfa >= 1.2 && < 1.3
    - tasty >= 1.0 && < 1.1
    - tasty-hunit >= 0.10 && < 0.11
    - temporary >= 1.2 && < 1.3
    - transformers >= 0.5 && < 0.6
